spring.application.name=projeto2

server.address=127.0.0.1
server.port=8080

spring.datasource.url=${PV2_URL}
spring.datasource.username=${PDB_USERNAME}
spring.datasource.password=${PDB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true